title: "Esha Sajjanhar"
description: "" 
url: "https://eshasajjanhar.github.io"
baseurl: "" 
# Navigation menu
nav_links:
  - title: "Research"
    url: "/research"
  - title: "Astrophotography"
    url: "/astrophotos"
  - title: "CV"
    url: "/assets/EshaSajjanhar-CV-Nov25.pdf"
theme: minima 
